#!/usr/bin/env bash

alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

alias ll='ls -lF --color=auto'
alias la='ls -alF --color=auto'
alias ls='ls -F --color=auto'

alias grep='grep --color=auto --exclude-dir=\.svn'
