#!/usr/bin/env bash

# Commands to be run for all interactive, non-login shells

# Source global definitions
if [ -f /etc/bashrc ] ; then
	source /etc/bashrc
fi

# Check to make sure we're really interactive.
# If so, run bash_interactive.
if [ -n "$PS1" -a -f ~/dotfiles/bash/bash_interactive ] ; then
    source ~/dotfiles/bash/bash_interactive
fi
